version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "traxler"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xmllcmujm5gz"
s3_prefix = "traxler"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "WebsiteDomain=\"nassau.network\""
